- name: Install required packages
  apt:
    name:
      - python3-pip
      - python3-venv
      - git
    state: present
    update_cache: yes

- name: Ensure pyenv and Python 3.5.10 is installed (custom step if not already installed)
  shell: |
    curl https://pyenv.run | bash
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    pyenv install -s 3.5.10
    pyenv virtualenv -f 3.5.10 myenv
  args:
    executable: /bin/bash
  become: false
